<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HuaweiCloud.GaussDB.DependencyInjection.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/GaussDB.DependencyInjection/GaussDB.DependencyInjection.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../GaussDB.Tests/GaussDB.Tests.csproj" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

</Project>
