<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <DebugType>portable</DebugType>
    <AssemblyName>GaussDB.Benchmarks</AssemblyName>
    <RootNamespace>HuaweiCloud.GaussDB.Benchmarks</RootNamespace>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);NPG9001</NoWarn> <!-- Converter-related APIs are experimental -->
    
    <!-- Suppress security audit errors as errors (especially from SqlClient) in this benchmark-only project -->
    <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/GaussDB/GaussDB.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../src/GaussDB.NodaTime/GaussDB.NodaTime.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../src/GaussDB.NetTopologySuite/GaussDB.NetTopologySuite.csproj" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>

</Project>
