<Project>
  <PropertyGroup>
    <GaussDBSupportedTargetFrameworks>net8.0;net9.0;net10.0</GaussDBSupportedTargetFrameworks>
    <GaussDBNativeAotTargetFrameworks>net8.0;net9.0;net10.0</GaussDBNativeAotTargetFrameworks>
    <VersionPrefix>0.1.1</VersionPrefix>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)GaussDB.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Copyright>Copyright 2025 © The GaussDB Development Team</Copyright>
    <PackageLicenseExpression>PostgreSQL</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/HuaweiCloudDeveloper/gaussdb-dotnet</PackageProjectUrl>
    <PackageIcon>gaussdb.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)gaussdb.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
