<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Description>GeoJSON plugin for GaussDB, allowing mapping of PostGIS geometry types to GeoJSON types.</Description>
    <PackageTags>$(PackageTags);postgis;geojson;spatial</PackageTags>
    <TargetFrameworks>$(GaussDBSupportedTargetFrameworks)</TargetFrameworks>
    <NoWarn>$(NoWarn);NPG9001</NoWarn> <!-- Converter-related APIs are experimental -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GeoJSON.Net" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GaussDB/GaussDB.csproj" SetTargetFramework="TargetFramework=$(TargetFramework)" />
    <ProjectReference Include="../GaussDB.SourceGenerators/GaussDB.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
</ItemGroup>
</Project>
