<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <Description>OpenTelemetry instrumentation for GaussDB.</Description>
        <TargetFrameworks>$(GaussDBSupportedTargetFrameworks)</TargetFrameworks>
        <PackageTags>$(PackageTags);opentelemetry;tracing;diagnostics;instrumentation</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GaussDB\GaussDB.csproj" SkipGetTargetFrameworkProperties="true" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry.API" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
