<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <RootNamespace>HuaweiCloud.GaussDB.PluginTests</RootNamespace>
  </PropertyGroup>  
  <ItemGroup>
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../src/GaussDB/GaussDB.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../src/GaussDB.NodaTime/GaussDB.NodaTime.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../src/GaussDB.Json.NET/GaussDB.Json.NET.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../GaussDB.Tests/GaussDB.Tests.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../src/GaussDB.NetTopologySuite/GaussDB.NetTopologySuite.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../src/GaussDB.GeoJSON/GaussDB.GeoJSON.csproj" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
</Project>
