<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>$(GaussDBSupportedTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);CS8002</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\GaussDB\GaussDB.csproj" SkipGetTargetFrameworkProperties="true" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="dotenv.net" />
    </ItemGroup>

    <ItemGroup>
      <None Condition="Exists('$(MSBuildProjectDirectory)\.env')" Update=".env">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
