name: Build

on:
  push:
    branches:
      - main
      - 'hotfix/**'
    tags:
      - '*'
  pull_request:

# Cancel previous PR branch commits (head_ref is only defined on PRs)
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        test_tfm: [net8.0, net9.0, net10.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NuGet Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Build.props', '**/Directory.Build.targets', 'Directory.Packages.props', 'global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build
        run: bash ./build.sh --target=build --framework=${{ matrix.test_tfm }}
        shell: bash
