name: Release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*' # e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Set Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  
    - name: Pack nuget package
      run: |
        bash ./build.sh
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
