<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Description>NodaTime plugin for GaussDB, allowing mapping of PostgreSQL date/time types to NodaTime types.</Description>
    <PackageTags>$(PackageTags);nodatime;date;time;</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TargetFrameworks>$(GaussDBSupportedTargetFrameworks)</TargetFrameworks>
    <NoWarn>$(NoWarn);NPG9001</NoWarn> <!-- Converter-related APIs are experimental -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaussDB\GaussDB.csproj" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../GaussDB.SourceGenerators/GaussDB.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" GlobalPropertiesToRemove="TargetFramework" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\GaussDBNodaTimeStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>GaussDBNodaTimeStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\GaussDBNodaTimeStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GaussDBNodaTimeStrings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
